### ISSUE TITLE
Unknown error while interacting with the clipboard:

### ISSUE THREAD

**Issue by BH1SCW** [cc-morning/share-clip#8]
急需这个哈哈

RUST_BACKTRACE=1 ./target/release/share-clip -u redis://:@docker -c cc-morning -n mac --secret-key  ./secret_key --public-key ./public_key
thread 'main' panicked at 'Failed to create clipboard!: Unknown { .. } - "Unknown error while interacting with the clipboard: Display parsing error"', src/clipboard.rs:42:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2e35f954ada0f0c777844dc4fa66684efe90a035/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/2e35f954ada0f0c777844dc4fa66684efe90a035/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/2e35f954ada0f0c777844dc4fa66684efe90a035/library/core/src/result.rs:1785:5
   3: share_clip::main::{{closure}}
   4: share_clip::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    2284700 abort (core dumped)  RUST_BACKTRACE=1 ./target/release/share-clip -u redis://:@docker -c cc-mornin

**Comment by hxcliff** [comment]
方便的话发下使用环境和完整的启动命令，linux有无桌面环境，使用的x11还是wayland
